# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Randstr < Formula
  desc "a Go random string generator"
  homepage "https://github.com/stuartinnes/randstr"
  version "0.1.2"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stuartinnes/randstr/releases/download/v0.1.2/randstr_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "97bff25818cf2d226635ebb4d41ba5e5ec09cb5b4378989f06650dbb73aa059a"
    end
    if Hardware::CPU.arm?
      url "https://github.com/stuartinnes/randstr/releases/download/v0.1.2/randstr_0.1.2_Darwin_arm64.tar.gz"
      sha256 "1753c4c2f97e2d8674f8362013e839f42d4acf0b853cfb03fcf722fee32ffd9f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stuartinnes/randstr/releases/download/v0.1.2/randstr_0.1.2_Linux_x86_64.tar.gz"
      sha256 "49696a20e3428c51ffdfb0c1e7edfe4a1cb017c04b0d2b39e330318d30e08073"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stuartinnes/randstr/releases/download/v0.1.2/randstr_0.1.2_Linux_arm64.tar.gz"
      sha256 "b8a810948776bb87f31951f84f9976e344ef773f1b00bc6aa4c66e9cac7df904"
    end
  end

  def install
    bin.install "randstr"
  end

  test do
    system "#{bin}/randstr -h"
  end
end
