# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Randstr < Formula
  desc "a Go random string generator"
  homepage "https://github.com/stuartinnes/randstr"
  version "0.1.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stuartinnes/randstr/releases/download/v0.1.0/randstr_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "cac56e89cbbf98ced581f687d69b27fc2270d1b17ced0a476c8ea9a41492beaa"
    end
    if Hardware::CPU.arm?
      url "https://github.com/stuartinnes/randstr/releases/download/v0.1.0/randstr_0.1.0_Darwin_arm64.tar.gz"
      sha256 "1f27d6e9471eafff69826aa7d3362fe71debef8cfe558daa77c9293b5a070a83"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stuartinnes/randstr/releases/download/v0.1.0/randstr_0.1.0_Linux_x86_64.tar.gz"
      sha256 "597a573d63b6ff52671521568e10c86914437887c9d38c5683d1cd7763d7dbe2"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stuartinnes/randstr/releases/download/v0.1.0/randstr_0.1.0_Linux_arm64.tar.gz"
      sha256 "014d3ec7778f9239fc29a652f44fb5def9326fd49d3d40252552945dd60c4c7f"
    end
  end

  def install
    bin.install "randstr"
  end

  test do
    system "#{bin}/randstr, -h"
  end
end
