# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stringthing < Formula
  desc "a handy CLI string toolkit"
  homepage "https://github.com/stuartinnes/stringthing"
  version "0.1.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stuartinnes/stringthing/releases/download/v0.1.0/stringthing_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "c27d227a496b18eb9a154e4d39ea53f5e1e647ab8cdce69db2847db93c31f433"
    end
    if Hardware::CPU.arm?
      url "https://github.com/stuartinnes/stringthing/releases/download/v0.1.0/stringthing_0.1.0_Darwin_arm64.tar.gz"
      sha256 "5d8cc53398a2dd022119c01d290525b31d7c037a0b9248587a1644e86fd2c85a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stuartinnes/stringthing/releases/download/v0.1.0/stringthing_0.1.0_Linux_x86_64.tar.gz"
      sha256 "1bf3ee677d253256a7936cd5347e6253a44568294fe837ff80d3e1df72e9df4d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stuartinnes/stringthing/releases/download/v0.1.0/stringthing_0.1.0_Linux_arm64.tar.gz"
      sha256 "20030daa95b5537b548750cd56c65e8899ba58afd02d5a3e71c9950decf305ef"
    end
  end

  def install
    bin.install "stringthing"
  end

  test do
    system "#{bin}/stringthing -h"
  end
end
