# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stringthing < Formula
  desc "a handy CLI string toolkit"
  homepage "https://github.com/stuartinnes/stringthing"
  version "0.1.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stuartinnes/stringthing/releases/download/v0.1.0/stringthing_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "3ed417af6edf68417b12f682f498bcb319f0af6b62ffcfc9ce50276260024658"
    end
    if Hardware::CPU.arm?
      url "https://github.com/stuartinnes/stringthing/releases/download/v0.1.0/stringthing_0.1.0_Darwin_arm64.tar.gz"
      sha256 "3898afdc30e2d1d2efc71ea4ffbc04096b0f5d969bb816398f2a291173b09d63"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stuartinnes/stringthing/releases/download/v0.1.0/stringthing_0.1.0_Linux_x86_64.tar.gz"
      sha256 "5d7ebbcbb201d5b80553a9ed2e25ca9f37cc7c4756f7568b89b4a6bc212fb933"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stuartinnes/stringthing/releases/download/v0.1.0/stringthing_0.1.0_Linux_arm64.tar.gz"
      sha256 "4a4686257313c96cb5d69139e581c5ec60137131c422e6e2f8feba623a178e56"
    end
  end

  def install
    bin.install "stringthing"
  end

  test do
    system "#{bin}/stringthing -h"
  end
end
