# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stringthing < Formula
  desc "a handy CLI string toolkit"
  homepage "https://github.com/stuartinnes/stringthing"
  version "0.1.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stuartinnes/stringthing/releases/download/v0.1.0/stringthing_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "6ef259875fa255de3e111b865c392ac1f72a0bdf937d79790be7e3c033e2c806"
    end
    if Hardware::CPU.arm?
      url "https://github.com/stuartinnes/stringthing/releases/download/v0.1.0/stringthing_0.1.0_Darwin_arm64.tar.gz"
      sha256 "a41b6dc102335c123c12318cdaedc48fd0b75ae0f8ed4eb47f5f794352fbd05d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stuartinnes/stringthing/releases/download/v0.1.0/stringthing_0.1.0_Linux_x86_64.tar.gz"
      sha256 "045006d75c861433feade7b57e1dd7dd1c32af7b68aef4afd49f6443eab097b8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stuartinnes/stringthing/releases/download/v0.1.0/stringthing_0.1.0_Linux_arm64.tar.gz"
      sha256 "92e4a14979d87332bcf5c8eb5f0b8540b71673c4b5efe1b6bb84fe331aa300a2"
    end
  end

  def install
    bin.install "stringthing"
  end

  test do
    system "#{bin}/stringthing -h"
  end
end
